# Generated by Django 4.0.3 on 2023-05-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
    ]
