# Generated by Django 4.0.3 on 2023-07-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='add_tiem',
            new_name='add_time',
        ),
    ]
